services:
  - type: web
    name: synergiq-llm-streamlit
    env: python
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: python -m streamlit run backend/conv.py --server.address 0.0.0.0 --server.port $PORT --server.headless true --browser.gatherUsageStats false
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: "3.10.13"
      - key: COHERE_API_KEY
        sync: false
